services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps # En desarrollo nos quedamos en la etapa de dependencias
    container_name: bna-plus-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev

  # Ejemplo de base de datos para el Dashboard (Opcional por ahora)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: bna_db
